MDScreen:

    MDNavigationLayout:

        ScreenManager:

            MDScreen:

                MDToolbar:
                    title: "Fenty File Previewer"
                    elevation: 10
                    md_bg_color: app.theme_cls.bg_light
                    pos_hint: {"top": 1}
                    left_action_items:
                        [['menu', lambda x: nav_drawer.set_state("open")]]


        MDNavigationDrawer:
            id: nav_drawer

            ContentNavigationDrawer: